#!/bin/bash
cd ..
rm -rf build
mkdir build
cd build
mkdir tmp
echo "Who are you?" | > prompt.txt
cmake .. -G Ninja \
-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
-DCMAKE_BUILD_TYPE=Release \
-DMNN_BUILD_SHARED_LIBS=OFF \
-DMNN_WIN_RUNTIME_MT=ON \
-DMNN_BUILD_LLM=ON \
-DMNN_SUPPORT_TRANSFORMER_FUSE=ON \
-DMNN_BUILD_AUDIO=ON \
-DMNN_AUDIO_TEST=ON \
-DPYMNN_AUDIO_API=ON \
-DMNN_OPENCL=ON \
-DMNN_USE_SSE=ON \
-DMNN_BUILD_TEST=ON \
-DCMAKE_CXX_FLAGS="-DDUMP_TALKER_PERFORMANCE -DENABLE_PERF_LOGGING"

ninja
