@echo off
cd ..
@REM mkdir build
cd build
cmake .. -G Ninja ^
-DCMAKE_POLICY_VERSION_MINIMUM=3.5 ^
-DCMAKE_BUILD_TYPE=Release ^
-DMNN_BUILD_SHARED_LIBS=ON ^
-DMNN_WIN_RUNTIME_MT=ON ^
-DMNN_CUDA=ON ^
-DMNN_BUILD_LLM=ON ^
-DMNN_SUPPORT_TRANSFORMER_FUSE=ON ^
-DMNN_BUILD_AUDIO=ON ^
-DMNN_AUDIO_TEST=ON ^
-DPYMNN_AUDIO_API=ON

ninja